// File: src/core/services/mockData.ts
import { Application } from '../domain/models/Application';

export const mockApplications: Application[] = [
  {
    id: '1',
    company: 'TechCorp',
    position: 'Frontend Developer',
    dateApplied: '2024-03-15',
    stage: 'Unassigned',
    type: 'frontend',
    tags: ['frontend'],
    lastUpdated: '2024-03-15',
    description: 'Full-time position focusing on React and modern frontend technologies',
    salary: '$80,000 - $120,000',
    location: 'San Francisco, CA',
    notes: 'Had initial chat with recruiter Sarah. Technical interview scheduled.',
    logs: [
      {
        id: '1',
        date: '2024-03-15',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
    ],
  },
  {
    id: '2',
    company: 'StartupInc',
    position: 'Full Stack Engineer',
    dateApplied: '2024-03-10',
    stage: 'Resume Submitted',
    type: 'fullstack',
    tags: ['fullstack'],
    lastUpdated: '2024-03-16',
    description: 'Early-stage startup building developer tools',
    salary: '$90,000 - $130,000',
    location: 'Remote',
    notes: 'Submitted via referral from David',
    logs: [
      {
        id: '1',
        date: '2024-03-10',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-03-16',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
    ],
  },
  {
    id: '3',
    company: 'Google',
    position: 'Software Engineer',
    dateApplied: '2024-03-12',
    stage: 'Interview Process',
    type: 'backend',
    tags: ['backend'],
    lastUpdated: '2024-03-17',
    description: 'L4 position in Cloud Infrastructure team',
    salary: '$130,000 - $180,000',
    location: 'Mountain View, CA',
    notes: 'Completed phone screen, preparing for onsite',
    logs: [
      {
        id: '1',
        date: '2024-03-12',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-03-15',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-03-17',
        fromStage: 'Resume Submitted',
        toStage: 'Interview Process',
        message: 'Scheduled for technical interview',
        source: 'manual',
      },
    ],
  },
  {
    id: '4',
    company: 'Facebook',
    position: 'Product Designer',
    dateApplied: '2024-03-18',
    stage: 'Offer',
    type: 'frontend',
    tags: ['frontend'],
    lastUpdated: '2024-03-18',
    description: 'Design position focusing on mobile app UX',
    salary: '$100,000 - $150,000',
    location: 'Menlo Park, CA',
    notes: 'Received verbal offer, negotiating terms',
    logs: [
      {
        id: '1',
        date: '2024-03-18',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-03-18',
        fromStage: 'Unassigned',
        toStage: 'Offer',
        message: 'Received verbal offer',
        source: 'manual',
      },
    ],
  },
  {
    id: '5',
    company: 'Amazon',
    position: 'Backend Engineer',
    dateApplied: '2024-03-20',
    stage: 'Rejected',
    type: 'backend',
    tags: ['backend'],
    lastUpdated: '2024-03-20',
    description: 'Mid-level position in AWS team',
    salary: '$110,000 - $160,000',
    location: 'Seattle, WA',
    notes: 'Application rejected after phone screen',
    logs: [
      {
        id: '1',
        date: '2024-03-20',
        fromStage: null,
        toStage: 'Rejected',
        message: 'Application rejected after phone screen',
        source: 'manual',
      },
    ],
  },
  {
    id: '6',
    company: 'Microsoft',
    position: 'Data Scientist',
    dateApplied: '2024-02-20',
    stage: 'Interview Process',
    type: 'data_scientist',
    tags: ['data', 'science'],
    lastUpdated: '2024-02-25',
    description: 'Position focusing on machine learning models for Azure',
    salary: '$100,000 - $150,000',
    location: 'Redmond, WA',
    notes: 'Completed data challenge, awaiting interview scheduling.',
    logs: [
      {
        id: '1',
        date: '2024-02-20',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-02-22',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-02-25',
        fromStage: 'Resume Submitted',
        toStage: 'Interview Process',
        message: 'Scheduled for data challenge',
        source: 'manual',
      },
    ],
  },
  {
    id: '7',
    company: 'Netflix',
    position: 'DevOps Engineer',
    dateApplied: '2024-01-10',
    stage: 'Offer',
    type: 'devops',
    tags: ['devops', 'infrastructure'],
    lastUpdated: '2024-01-20',
    description: 'Role focusing on cloud infrastructure management',
    salary: '$110,000 - $160,000',
    location: 'Los Gatos, CA',
    notes: 'Received and accepted offer.',
    logs: [
      {
        id: '1',
        date: '2024-01-10',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-01-12',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-01-15',
        fromStage: 'Resume Submitted',
        toStage: 'Interview Process',
        message: 'Scheduled for technical interview',
        source: 'manual',
      },
      {
        id: '4',
        date: '2024-01-20',
        fromStage: 'Interview Process',
        toStage: 'Offer',
        message: 'Received formal offer',
        source: 'manual',
      },
    ],
  },
  // Add more applications as needed
];