// File: src/core/services/mockData.ts
import { Application } from '../../domain/interfaces/IApplication';

export const mockApplications: Application[] = [
  {
    id: '1',
    company: 'TechCorp',
    position: 'Frontend Developer',
    dateApplied: '2024-03-15',
    stage: 'Unassigned',
    type: 'frontend',
    tags: ['frontend'],
    lastUpdated: '2024-03-15',
    description: 'Full-time position focusing on React and modern frontend technologies',
    salary: '$80,000 - $120,000',
    location: 'San Francisco, CA',
    notes: 'Had initial chat with recruiter Sarah. Technical interview scheduled.',
    logs: [
      {
        id: '1',
        date: '2024-03-15',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
    ],
  },
  {
    id: '2',
    company: 'StartupInc',
    position: 'Full Stack Engineer',
    dateApplied: '2024-03-10',
    stage: 'Resume Submitted',
    type: 'fullstack',
    tags: ['fullstack'],
    lastUpdated: '2024-03-16',
    description: 'Early-stage startup building developer tools',
    salary: '$90,000 - $130,000',
    location: 'Remote',
    notes: 'Submitted via referral from David',
    logs: [
      {
        id: '1',
        date: '2024-03-10',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-03-16',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
    ],
  },
  {
    id: '3',
    company: 'Google',
    position: 'Software Engineer',
    dateApplied: '2024-03-12',
    stage: 'Interview Process',
    type: 'backend',
    tags: ['backend'],
    lastUpdated: '2024-03-17',
    description: 'L4 position in Cloud Infrastructure team',
    salary: '$130,000 - $180,000',
    location: 'Mountain View, CA',
    notes: 'Completed phone screen, preparing for onsite',
    logs: [
      {
        id: '1',
        date: '2024-03-12',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-03-15',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-03-17',
        fromStage: 'Resume Submitted',
        toStage: 'Interview Process',
        message: 'Scheduled for technical interview',
        source: 'manual',
      },
    ],
  },
  {
    id: '4',
    company: 'Facebook',
    position: 'Product Designer',
    dateApplied: '2024-03-18',
    stage: 'Offer',
    type: 'frontend',
    tags: ['frontend'],
    lastUpdated: '2024-03-18',
    description: 'Design position focusing on mobile app UX',
    salary: '$100,000 - $150,000',
    location: 'Menlo Park, CA',
    notes: 'Received verbal offer, negotiating terms',
    logs: [
      {
        id: '1',
        date: '2024-03-18',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-03-18',
        fromStage: 'Unassigned',
        toStage: 'Offer',
        message: 'Received verbal offer',
        source: 'manual',
      },
    ],
  },
  {
    id: '5',
    company: 'Amazon',
    position: 'Backend Engineer',
    dateApplied: '2024-03-20',
    stage: 'Rejected',
    type: 'backend',
    tags: ['backend'],
    lastUpdated: '2024-03-20',
    description: 'Mid-level position in AWS team',
    salary: '$110,000 - $160,000',
    location: 'Seattle, WA',
    notes: 'Application rejected after phone screen',
    logs: [
      {
        id: '1',
        date: '2024-03-20',
        fromStage: null,
        toStage: 'Rejected',
        message: 'Application rejected after phone screen',
        source: 'manual',
      },
    ],
  },
  {
    id: '6',
    company: 'Microsoft',
    position: 'Data Scientist',
    dateApplied: '2024-02-20',
    stage: 'Interview Process',
    type: 'data_scientist',
    tags: ['data', 'science'],
    lastUpdated: '2024-02-25',
    description: 'Position focusing on machine learning models for Azure',
    salary: '$100,000 - $150,000',
    location: 'Redmond, WA',
    notes: 'Completed data challenge, awaiting interview scheduling.',
    logs: [
      {
        id: '1',
        date: '2024-02-20',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-02-22',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-02-25',
        fromStage: 'Resume Submitted',
        toStage: 'Interview Process',
        message: 'Scheduled for data challenge',
        source: 'manual',
      },
    ],
  },
  {
    id: '7',
    company: 'Netflix',
    position: 'DevOps Engineer',
    dateApplied: '2024-01-10',
    stage: 'Offer',
    type: 'devops',
    tags: ['devops', 'infrastructure'],
    lastUpdated: '2024-01-20',
    description: 'Role focusing on cloud infrastructure management',
    salary: '$110,000 - $160,000',
    location: 'Los Gatos, CA',
    notes: 'Received and accepted offer.',
    logs: [
      {
        id: '1',
        date: '2024-01-10',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-01-12',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-01-15',
        fromStage: 'Resume Submitted',
        toStage: 'Interview Process',
        message: 'Scheduled for technical interview',
        source: 'manual',
      },
      {
        id: '4',
        date: '2024-01-20',
        fromStage: 'Interview Process',
        toStage: 'Offer',
        message: 'Received formal offer',
        source: 'manual',
      },
    ],
  },
  {
    id: '8',
    company: 'LinkedIn',
    position: 'Software Engineer',
    dateApplied: '2024-04-05',
    stage: 'Resume Submitted',
    type: 'fullstack',
    tags: ['fullstack', 'linkedin'],
    lastUpdated: '2024-04-05',
    description: 'Develop and maintain LinkedIn features and services',
    salary: '$100,000 - $150,000',
    location: 'Sunnyvale, CA',
    notes: 'Applied through LinkedIn portal.',
    logs: [],
  },
  {
    id: '9',
    company: 'Apple',
    position: 'iOS Developer',
    dateApplied: '2024-04-20',
    stage: 'Interview Process',
    type: 'frontend',
    tags: ['iOS', 'frontend'],
    lastUpdated: '2024-04-20',
    description: 'Work on the next generation of iOS applications',
    salary: '$120,000 - $170,000',
    location: 'Cupertino, CA',
    notes: 'Awaiting response for interview scheduling.',
    logs: [],
  },
  {
    id: '10',
    company: 'Tesla',
    position: 'Machine Learning Engineer',
    dateApplied: '2024-05-10',
    stage: 'Resume Submitted',
    type: 'data_scientist',
    tags: ['machine learning', 'data'],
    lastUpdated: '2024-05-10',
    description: 'Develop ML models for autonomous driving systems',
    salary: '$130,000 - $180,000',
    location: 'Palo Alto, CA',
    notes: 'Referral from current Tesla employee.',
    logs: [],
  },
  {
    id: '11',
    company: 'Adobe',
    position: 'UX Designer',
    dateApplied: '2024-05-25',
    stage: 'Offer',
    type: 'frontend',
    tags: ['design', 'ux'],
    lastUpdated: '2024-06-01',
    description: 'Design user experiences for Adobe Creative Cloud',
    salary: '$90,000 - $140,000',
    location: 'San Jose, CA',
    notes: 'Received offer, considering options.',
    logs: [],
  },
  {
    id: '12',
    company: 'Salesforce',
    position: 'Cloud Architect',
    dateApplied: '2024-06-15',
    stage: 'Interview Process',
    type: 'backend',
    tags: ['cloud', 'architecture'],
    lastUpdated: '2024-06-15',
    description: 'Architect scalable cloud solutions for Salesforce products',
    salary: '$140,000 - $200,000',
    location: 'San Francisco, CA',
    notes: 'Technical interview scheduled for next week.',
    logs: [],
  },
  {
    id: '13',
    company: 'Uber',
    position: 'Data Engineer',
    dateApplied: '2024-07-01',
    stage: 'Resume Submitted',
    type: 'data_scientist',
    tags: ['data', 'engineering'],
    lastUpdated: '2024-07-01',
    description: 'Build and maintain data pipelines for Uber\'s analytics platform',
    salary: '$110,000 - $160,000',
    location: 'San Francisco, CA',
    notes: 'Submitted application via career site.',
    logs: [],
  },
  {
    id: '14',
    company: 'Airbnb',
    position: 'Backend Developer',
    dateApplied: '2024-07-20',
    stage: 'Rejected',
    type: 'backend',
    tags: ['backend', 'nodejs'],
    lastUpdated: '2024-07-25',
    description: 'Develop backend services for Airbnb\'s platform',
    salary: '$100,000 - $150,000',
    location: 'San Francisco, CA',
    notes: 'Received rejection email after initial screening.',
    logs: [],
  },
  {
    id: '15',
    company: 'Spotify',
    position: 'Data Analyst',
    dateApplied: '2024-08-05',
    stage: 'Resume Submitted',
    type: 'data_scientist',
    tags: ['data', 'analytics'],
    lastUpdated: '2024-08-05',
    description: 'Analyze user data to improve Spotify\'s recommendation algorithms',
    salary: '$85,000 - $130,000',
    location: 'New York, NY',
    notes: 'Applied through employee referral.',
    logs: [],
  },
  {
    id: '16',
    company: 'Dropbox',
    position: 'DevOps Engineer',
    dateApplied: '2024-08-20',
    stage: 'Interview Process',
    type: 'devops',
    tags: ['devops', 'cloud'],
    lastUpdated: '2024-08-20',
    description: 'Manage and optimize Dropbox\'s cloud infrastructure',
    salary: '$115,000 - $170,000',
    location: 'San Francisco, CA',
    notes: 'Interview process initiated, awaiting scheduling.',
    logs: [],
  },
  {
    id: '17',
    company: 'Oracle',
    position: 'Database Administrator',
    dateApplied: '2024-09-01',
    stage: 'Resume Submitted',
    type: 'backend',
    tags: ['database', 'sql'],
    lastUpdated: '2024-09-01',
    description: 'Maintain and optimize Oracle databases for enterprise clients',
    salary: '$90,000 - $140,000',
    location: 'Austin, TX',
    notes: 'Applied through Oracle career portal.',
    logs: [],
  },
  {
    id: '18',
    company: 'IBM',
    position: 'AI Researcher',
    dateApplied: '2024-09-15',
    stage: 'Offer',
    type: 'data_scientist',
    tags: ['AI', 'research'],
    lastUpdated: '2024-09-20',
    description: 'Conduct research on artificial intelligence and machine learning',
    salary: '$120,000 - $180,000',
    location: 'Armonk, NY',
    notes: 'Received offer, reviewing terms.',
    logs: [],
  },
  {
    id: '19',
    company: 'Snapchat',
    position: 'Mobile Developer',
    dateApplied: '2024-10-01',
    stage: 'Resume Submitted',
    type: 'frontend',
    tags: ['mobile', 'iOS', 'android'],
    lastUpdated: '2024-10-01',
    description: 'Develop and maintain Snapchat mobile applications',
    salary: '$95,000 - $145,000',
    location: 'Los Angeles, CA',
    notes: 'Applied via recruiter contact.',
    logs: [],
  },
  {
    id: '20',
    company: 'Twitter',
    position: 'Security Engineer',
    dateApplied: '2024-10-20',
    stage: 'Interview Process',
    type: 'backend',
    tags: ['security', 'backend'],
    lastUpdated: '2024-10-20',
    description: 'Ensure the security of Twitter\'s platform and user data',
    salary: '$125,000 - $175,000',
    location: 'San Francisco, CA',
    notes: 'Security interview scheduled for next month.',
    logs: [],
  },
  {
    id: '21',
    company: 'Shopify',
    position: 'E-commerce Developer',
    dateApplied: '2024-11-01',
    stage: 'Resume Submitted',
    type: 'fullstack',
    tags: ['e-commerce', 'fullstack'],
    lastUpdated: '2024-11-01',
    description: 'Develop and enhance Shopify\'s e-commerce platform features',
    salary: '$100,000 - $155,000',
    location: 'Ottawa, ON',
    notes: 'Applied through Shopify careers page.',
    logs: [],
  },
  {
    id: '22',
    company: 'Pinterest',
    position: 'Data Scientist',
    dateApplied: '2024-11-10',
    stage: 'Rejected',
    type: 'data_scientist',
    tags: ['data', 'machine learning'],
    lastUpdated: '2024-11-15',
    description: 'Analyze user data to improve Pinterest\'s recommendation systems',
    salary: '$110,000 - $160,000',
    location: 'San Francisco, CA',
    notes: 'Received rejection after first interview.',
    logs: [],
  },
  {
    id: '23',
    company: 'Slack',
    position: 'Product Manager',
    dateApplied: '2024-11-18',
    stage: 'Resume Submitted',
    type: 'management',
    tags: ['product', 'management'],
    lastUpdated: '2024-11-18',
    description: 'Manage product lifecycle for Slack\'s collaboration tools',
    salary: '$105,000 - $160,000',
    location: 'San Francisco, CA',
    notes: 'Submitted application, awaiting response.',
    logs: [],
  },
  {
    id: '24',
    company: 'Square',
    position: 'Financial Analyst',
    dateApplied: '2024-12-01',
    stage: 'Resume Submitted',
    type: 'finance',
    tags: ['finance', 'analysis'],
    lastUpdated: '2024-12-01',
    description: 'Analyze financial data to support Square\'s business decisions',
    salary: '$85,000 - $130,000',
    location: 'San Francisco, CA',
    notes: 'Applied through internal referral.',
    logs: [],
  },
  {
    id: '25',
    company: 'PayPal',
    position: 'Backend Developer',
    dateApplied: '2024-12-10',
    stage: 'Interview Process',
    type: 'backend',
    tags: ['backend', 'payments'],
    lastUpdated: '2024-12-10',
    description: 'Develop backend services for PayPal\'s payment processing systems',
    salary: '$100,000 - $150,000',
    location: 'San Jose, CA',
    notes: 'Interview process started, technical interview next week.',
    logs: [],
  },
  {
    id: '26',
    company: 'Stripe',
    position: 'Site Reliability Engineer',
    dateApplied: '2024-12-20',
    stage: 'Resume Submitted',
    type: 'devops',
    tags: ['sre', 'devops'],
    lastUpdated: '2024-12-20',
    description: 'Ensure the reliability and scalability of Stripe\'s payment infrastructure',
    salary: '$130,000 - $190,000',
    location: 'San Francisco, CA',
    notes: 'Applied via Stripe career portal.',
    logs: [],
  },
  {
    id: '27',
    company: 'Zoom',
    position: 'Quality Assurance Engineer',
    dateApplied: '2025-01-05',
    stage: 'Resume Submitted',
    type: 'qa',
    tags: ['quality assurance', 'testing'],
    lastUpdated: '2025-01-05',
    description: 'Test and ensure the quality of Zoom\'s video conferencing products',
    salary: '$90,000 - $140,000',
    location: 'San Jose, CA',
    notes: 'Applied through recruiter contact.',
    logs: [],
  },
  {
    id: '28',
    company: 'ByteDance',
    position: 'AI Engineer',
    dateApplied: '2024-04-10',
    stage: 'Offer',
    type: 'data_scientist',
    tags: ['AI', 'machine learning'],
    lastUpdated: '2024-04-25',
    description: 'Develop AI models for content recommendation systems',
    salary: '$125,000 - $180,000',
    location: 'Beijing, China',
    notes: 'Received and accepted the offer.',
    logs: [
      {
        id: '1',
        date: '2024-04-10',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-04-12',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-04-15',
        fromStage: 'Resume Submitted',
        toStage: 'Online Assessment',
        message: 'Completed online coding assessment',
        source: 'manual',
      },
      {
        id: '4',
        date: '2024-04-20',
        fromStage: 'Online Assessment',
        toStage: 'Interview Process',
        message: 'Scheduled for technical interviews',
        source: 'manual',
      },
      {
        id: '5',
        date: '2024-04-25',
        fromStage: 'Interview Process',
        toStage: 'Offer',
        message: 'Received formal job offer',
        source: 'manual',
      },
    ],
  },
  {
    id: '29',
    company: 'Netflix',
    position: 'Backend Developer',
    dateApplied: '2024-05-05',
    stage: 'Interview Process',
    type: 'backend',
    tags: ['backend', 'nodejs'],
    lastUpdated: '2024-05-18',
    description: 'Develop backend services for Netflix streaming platform',
    salary: '$115,000 - $170,000',
    location: 'Los Gatos, CA',
    notes: 'Completed first round of interviews, awaiting next steps.',
    logs: [
      {
        id: '1',
        date: '2024-05-05',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-05-07',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-05-10',
        fromStage: 'Resume Submitted',
        toStage: 'Online Assessment',
        message: 'Completed online technical assessment',
        source: 'manual',
      },
      {
        id: '4',
        date: '2024-05-15',
        fromStage: 'Online Assessment',
        toStage: 'Interview Process',
        message: 'Scheduled for onsite interviews',
        source: 'manual',
      },
    ],
  },
  {
    id: '30',
    company: 'Adobe',
    position: 'Senior UX Designer',
    dateApplied: '2024-06-01',
    stage: 'Rejected',
    type: 'frontend',
    tags: ['design', 'ux'],
    lastUpdated: '2024-06-10',
    description: 'Lead UX design projects for Adobe Creative Suite',
    salary: '$95,000 - $140,000',
    location: 'San Jose, CA',
    notes: 'Received rejection after design review.',
    logs: [
      {
        id: '1',
        date: '2024-06-01',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-06-03',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-06-05',
        fromStage: 'Resume Submitted',
        toStage: 'Interview Process',
        message: 'Scheduled for portfolio review',
        source: 'manual',
      },
      {
        id: '4',
        date: '2024-06-10',
        fromStage: 'Interview Process',
        toStage: 'Rejected',
        message: 'Application rejected after design review',
        source: 'manual',
      },
    ],
  },
  {
    id: '31',
    company: 'Spotify',
    position: 'Full Stack Developer',
    dateApplied: '2024-07-15',
    stage: 'Offer',
    type: 'fullstack',
    tags: ['fullstack', 'spotify'],
    lastUpdated: '2024-07-30',
    description: 'Develop and maintain Spotify\'s web and mobile applications',
    salary: '$110,000 - $160,000',
    location: 'New York, NY',
    notes: 'Received and accepted the offer.',
    logs: [
      {
        id: '1',
        date: '2024-07-15',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-07-17',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-07-20',
        fromStage: 'Resume Submitted',
        toStage: 'Online Assessment',
        message: 'Completed online coding challenge',
        source: 'manual',
      },
      {
        id: '4',
        date: '2024-07-25',
        fromStage: 'Online Assessment',
        toStage: 'Interview Process',
        message: 'Scheduled for technical and HR interviews',
        source: 'manual',
      },
      {
        id: '5',
        date: '2024-07-30',
        fromStage: 'Interview Process',
        toStage: 'Offer',
        message: 'Received formal job offer',
        source: 'manual',
      },
    ],
  },
  {
    id: '32',
    company: 'Tesla',
    position: 'Machine Learning Engineer',
    dateApplied: '2024-08-10',
    stage: 'Interview Process',
    type: 'data_scientist',
    tags: ['machine learning', 'data'],
    lastUpdated: '2024-08-25',
    description: 'Develop ML models for autonomous driving systems',
    salary: '$135,000 - $190,000',
    location: 'Palo Alto, CA',
    notes: 'Interview process initiated, awaiting scheduling.',
    logs: [
      {
        id: '1',
        date: '2024-08-10',
        fromStage: null,
        toStage: 'Unassigned',
        message: 'Application created',
        source: 'manual',
      },
      {
        id: '2',
        date: '2024-08-12',
        fromStage: 'Unassigned',
        toStage: 'Resume Submitted',
        message: 'Resume submitted to hiring manager',
        source: 'manual',
      },
      {
        id: '3',
        date: '2024-08-15',
        fromStage: 'Resume Submitted',
        toStage: 'Online Assessment',
        message: 'Completed online machine learning assessment',
        source: 'manual',
      },
      {
        id: '4',
        date: '2024-08-20',
        fromStage: 'Online Assessment',
        toStage: 'Interview Process',
        message: 'Scheduled for technical interviews',
        source: 'manual',
      },
    ],
  },
];